#!/bin/bash

function usage() {
    echo "aliping -i='interval' -d='duration' -t='hosts'"
    echo ""
    echo "This script pings 'hosts' every 'interval' seconds and lasts for 'duration' seconds."
    echo ""
    echo "-h --help"
    echo "-i --interval. Default: '1'."
    echo "-d --duration. Default: '3600 * 24 * 7', i.e., a weak."
    echo "-t --hosts. Default: 'nc1 nc2 nc3 sc1 sc2 sc3 ec1 ec2 ec3'."
    echo ""
}

interval=1	# ping once a second
duration=$[ 3600 * 24 * 7 ]	# last for a week
hosts="nc1 nc2 nc3 sc1 sc2 sc3 ec1 ec2 ec3"	# run on all 9 ECSes

# parse the arguments: -h (--help), -i (--interval), -d (--duration), -t (--hosts)
while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
        -i | --interval)
            interval=$VALUE
            ;;
        -d | --duration)
            duration=$VALUE
            ;;
	-t | --hosts)
	    hosts=$VALUE
	    ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

PINGDIR="aliping-logs"

echo -e "\n The present working directory is: $PWD.\n 
This script will create a subdirectory called $PINGDIR and store ping data into it.\n
Pause 10 second now.\n
Press Ctrl+C to break."

sleep 10s

if [ ! -d "$PINGDIR" ]; then
	mkdir $PINGDIR
fi

LANG=en_us_8859_1

for host in $hosts; do
	if [ $host != $HOSTNAME ]; then
		log="$PINGDIR/$host-ping-log"
		if [ ! -f $log ]; then  # create log file if not exists
			touch $log
		fi

		if [ ! -s $log ]; then
			echo -en '\n'  >> $log  # writing empty line
		fi
		date +"%A, %B %d %Y" >> $log  # writing date
		echo -en '\n'  >> $log  # writing empty line

		ping $host >> $log 2>&1 &
	fi
done 