#!/bin/bash

# This script collects ping data from remote hosts.
# It needs to be generalized.

hosts="nc1 nc2 nc3 sc1 sc2 sc3 ec1 ec2 ec3"

for host in $hosts; do
	scp -r root@$host:~/aliping-logs ~/git-projects/github-projects/aliyun-projects/aliyun-ecs-projects/aliyun-ecs-ping-project/aliyun-ping-raw-data/$host/ &
done
